### ISSUE TITLE
Review how BCO-DMO is tracking Google Analytics Events

### ISSUE THREAD

**Issue by ashepherd** [BCODMO/CounterProject#4]
- [ ] Note what events we track and how
- [ ] Note what fields of the Google Analytics Event Tracking we are using
- [ ] Review with Adam

Here is our Javascript snippet used to tracking events:
https://www.bco-dmo.org/sites/all/modules/features/osprey_usage_stats/js/event-tracker.js
```
/**
 * @see https://developers.google.com/analytics/devguides/collection/analyticsjs/events
 */
function trackEvent(category, action, label, value, action_type, url) {
  if (typeof ga !== 'undefined') {
    if (value != undefined) {
      ga('send', 'event', {
        eventCategory: category,
        eventAction: action,
        eventLabel: label
      });
    }
    else {
      ga('send', 'event', {
        eventCategory: category,
        eventAction: action,
        eventLabel: label,
        eventValue: value
      });
    }
  }
  else if (typeof console !== 'undefined'&& console != undefined && typeof console.log == 'function') {
    if (value == undefined) {
      value = '';
    }
    console.log('Track event: ' + category + '::' + action + ' for ' + label + ' ' + value);
  }

  if (undefined != action_type && undefined != url) {
    switch (action_type) {
      case 'window.open:_blank':
        window.open(url, '_blank');
        break;

      case 'window.location.href':
        window.location.href = url;
        break;
    }
  }
}
;
```

On Dataset pages, here is the Google Analytics script:
Sample dataset page: https://www.bco-dmo.org/dataset/526852
```
<script type="text/javascript">
--
  | <!--//--><![CDATA[//><!--
  | (function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]\|\|function(){(i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.bco-dmo.org/sites/default/files/googleanalytics/analytics.js?qh19zd","ga");ga("create", "UA-16906710-4", {"cookieDomain":"auto","allowLinker":true});ga("require", "linker");ga("linker:autoLink", ["www.bco-dmo.org","www.bcodmo.org","osprey.bco-dmo.org"]);ga("send", "pageview");
  | //--><!]]>
  | </script>
```

Uses of `trackEvent()`:

View the page source of https://www.bco-dmo.org/dataset/526852 and search for `trackEvent(`

Example: 
```
onClick="trackEvent('Get Data Button','view','http://lod.bco-dmo.org/id/dataset/526852','undefined','window.open:_blank','http://dmoserv3.bco-dmo.org/jg/serv/BCO-DMO/JeDI/JeDI.brev0%7Bdir=dmoserv3.whoi.edu/jg/dir/BCO-DMO/JeDI/,info=dmoserv3.bco-dmo.org/jg/info/BCO-DMO/JeDI/JeDI%7D');"
```

**Comment by Arcaderat** [comment]
Everything except page views from the mapping table of events to views/downloads ( #21 ) is tracked by an event with Event Label being the dataset's URL and Event Category being the type of event.
